### ISSUE TITLE
Issue with multiple autocomplete component in the same page.

### ISSUE THREAD

**Issue by MehdiM62** [gmerabishvili/angular-ng-autocomplete#23]
Thank you for providing the autocomplete component. I am using this component for multiple fields within a page. The issue I encounter is multiple dropdowns could be opened at the same time as demonstrated within below screenshot. I was wondering if you could have a look at this issue and help me to figure out a way to avoid this behavior.

![image](https://user-images.githubusercontent.com/19629619/61610175-eb05c900-ac8a-11e9-9d5d-298b804cbafd.png)

Step to reproduce:
1-Select an element from the first field
2-click on the second field
3-click on the close button(x) on the first field
4-click on the close button (x) on the available options.

**Comment by gmerabishvili** [comment]
Hello, The issue is resolved. Please update to latest 1.1.14 version. Thank you!

**Comment by JojiePalahang** [comment]
@gmerabishvili  - tried to test again, but issue still there.

**Comment by MehdiM62** [comment]
Hello @gmerabishvili,

Thanks for the update, the reported issue have been fixed for large screen, if the screen size small (laptop screen) or resizing the browser window small still the issue is reproduceable.

Step to reproduce:
1- Go to the simulator (https://stackblitz.com/edit/angular-ng-autocomplete-with-forms)
2- Make the browser window small.
3- Choose an option form the top component.
4- Choose an option form the bottom component.
5- Click the close icon (X) of the top component.
6- Click the close icon (X) of the bottom component.
![image](https://user-images.githubusercontent.com/19629619/62264636-530a9b00-b453-11e9-88a9-74dfecb1bb8f.png)

**Comment by Welborn09** [comment]
I am having the same issues as the OP. 

Could there be a way to setup a property that would hold the element that is focused and when the panel is populated it would use the reference of that focused control to pass data back to the focused control, leaving the other autocomplete controls alone?

A bad option I almost went down was to get the control name in the onFocus event and use a switch(controlname) and from there and call the appropriate route then setting the data object for that control.

But that was a bad option.

**Comment by gmerabishvili** [comment]
Hello @Welborn09, the issue will be fixed in next version, for the temporary solution you can set .overlay element to position: fixed and will resolve the issue. Thank you!

**Comment by Welborn09** [comment]
Thank you, sir. Great work on the library as well.

**Comment by gmerabishvili** [comment]
Hello @MehdiM62 @JojiePalahang @Welborn09 The issue is fixed. Please upgrade to latest 2.0.2 version. Thank you!

**Comment by SushmaSagar042** [comment]
Hello @gmerabishvili  I am trying to use multiple ng-autocomplete in same form. But the problem is it doesn't work with different keywords. for ex first ng-autocomplete I will give keyword = 'name, for second ng- autocomplete If I give keyword1='name2'. It doesn't work.

Cannot read property 'toLowerCase' of undefined
    at angular-ng-autocomplete.js:517
    at Array.filter (<anonymous>)
    at AutocompleteComponent.defaultFilterFunction (angular-ng-autocomplete.js:506)
    at AutocompleteComponent.filterList (angular-ng-autocomplete.js:491)
    at AutocompleteComponent.handleOpen (angular-ng-autocomplete.js:760)
    at AutocompleteComponent.setPanelState (angular-ng-autocomplete.js:655)
    at AutocompleteComponent.handleFocus (angular-ng-autocomplete.js:793)
    at AutocompleteComponent_Template_input_focus_2_listener (angular-ng-autocomplete.js:1229)
    at executeListenerWithErrorHandling (core.js:14994)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15029)

How to use multiple ng-autocomplete with diffrent keywords

**Comment by gmerabishvili** [comment]
@SushmaSagar042  I think you have some problem with your implementation. ng-autocomplete works with different keywords out of the box. Please re-check the examples on Doc page.

**Comment by yasoobrizvi** [comment]
Hello @gmerabishvili, I'm also facing the same issue in using 2 autocomplete, even though I've given different names for [itemTemplate] and [searchKeyword].
